services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: node_app
    restart: always
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=dev
      - DB_PASSWORD=123456
      - DB_NAME=database
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Importante!
    stdin_open: true
    tty: true

    command: npm run dev

    depends_on:
      - db
    networks:
      - node  

  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    volumes:
      - ../mysql:/var/lib/mysql
    networks:
      - node
    ports:
      - "3306:3306"

networks:
  node:
    driver: bridge